name: Build
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Build the app
        run: gradle assembleRelease
      - uses: actions/upload-artifact@v3
        with:
            name: ladb
            path: app/build/outputs/*
        
